version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotstardb
    ports:
      - "3306:3306"

  app:
    image: hotstar-app:latest
    depends_on:
      - db
    ports:
      - "9090:8080"

